### ISSUE TITLE
Error: Failed to update ref: HttpError: Update is not a fast forward

### ISSUE THREAD

**Issue by tmilar** [zofrex/mirror-branch#6] opened 2022-09-13 10:40 UTC
Hi,

I've been trying to put this job to use but I'm always getting this error.

My goal is to push to a `master` branch, then, do a merge commit and push to `develop`, **without using force**. 

The config is as follows:

```yml
      - name: Mirror branch master -> develop
        # Attempt to merge changes to develop.
        id: mirror
        uses: zofrex/mirror-branch@v1
        with:
          target-branch: develop
          force: false
          token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by zofrex** [comment] 2022-10-31 22:13
With `force` set to `false`, this will only work if the commit sha you are pushing to the develop branch is a descendant of the current HEAD of the develop branch, if that makes sense. Otherwise it will fail with this error.

If you want to first create a merge between the two branches, that's not something this action can do. This action is really fast because, rather than checkout the entire repository and act on that, it acts via the Github API. Via the API it can update the commit a branch points to, but it is not possible via the API (as far as I know) to create a merge commit.

I would recommend writing (or finding) an action that checks out the repository, creates the merge, and pushes the result.

Does that makes sense? Did I understand the issue correctly?

**Comment by zofrex** [comment] 2023-05-30 08:55
Closing due to no updates — I'm reasonably sure this is expected behaviour, given the information supplied.

**Closed as not planned** 2023-05-30 08:54 UTC
